config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "restaurants#index"

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end

  # devise_scope :user do
  #   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/endorsement.rb
class Endorsement < ApplicationRecord
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :reviews,
        -> { extending WithUserAssociationExtension },
        dependent: :destroy

  belongs_to :user
  validates :name, length: { minimum: 3 }, uniqueness: true

  searchkick

  def average_rating
      return 'N/A' if reviews.none?
      reviews.average(:rating)
  end


end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: {scope: :restaurant, message: 'has reviewed this restaurant already'}
  belongs_to :user
  belongs_to :restaurant
  has_many :endorsements
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] &&  session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include?(restaurant)    
  end


end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: {new_endorsement_count: @review.endorsements.count}
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :find_by_params, only: [:show, :edit, :update,
                                        :destroy, :restaurant_owner]
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :restaurant_owner, only: [:update, :destroy, :edit]

  def index
    query = params[:q].presence || "*"
    @restaurants = Restaurant.search(query)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end

  def find_by_params
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_owner
    unless @restaurant.user_id == current_user.id
      flash[:notice] = 'Permission denied: only owner has edit/delete privileges'
      redirect_to restaurants_path
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build_with_user(review_params, current_user)

    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
      else
        render :new
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end

    def failure
      redirect_to root_path
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating.round)
    "★" * rating.round + "☆" * remainder
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpClone</title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  </head>

  <body>
    <% if user_signed_in? %>
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Yelp Clone</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Add Restaurant", new_restaurant_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    <% else %>
    <nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Yelp Clone</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign in", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    <% end %>

    <div class="container">
      <% if notice %>
        <div class="alert alert-info" role="alert"><%= notice %></div>
      <% end %>

      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>

      <%= link_to "All restaurants", restaurants_path %>
      <%= form_tag restaurants_path, method: :get do %>
        <%= text_field_tag :q, nil, placeholder: "Search" %>
      <% end %>


      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, html: {multipart: true} do |field| %>
  <div class="form-group">
    <%= field.label :name %>
    <%= field.text_field :name, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= field.label :description %>
    <%= field.text_area :description, rows: 5, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= field.file_field :image %>
  </div>
  <%= field.submit :class => 'btn btn-primary' %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h3 class="text-center">Edit Restaurant</h3>

  <%= render "form" %>

</div>

app/views/restaurants/index.html.erb
<p> Found <%= @restaurants.length %> restaurants to display: </p>

<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <div class="restaurant-index">
      <h2 class= "restaurant-name"><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>

      <h3 class="restaurant-rating"> Average rating: <%= star_rating(restaurant.average_rating) %></h3>

      <div class="restaurant-panel">

        <div class="restaurant-thumb">
          <% if restaurant.image_file_name %>
            <%= image_tag restaurant.image.url(:medium) %>
          <% end %>
        </div>

        <div class="restaurant-description">
          <h4> Description: </h4>
          <p><%= restaurant.description %></p>
        </div>

        <div class="restaurant-reviews">
          <% if restaurant.reviews.any? %>
            <h4> Reviews: </h4>
            <% restaurant.reviews.each do |review| %>
              <%= review.thoughts %> <br>
                <%= link_to "Endorse Review", review_endorsements_path(review), class: 'endorsements-link'%>
                <span class="endorsements_count"><%= review.endorsements.count %> </span>
              <%= 'endorsement'.pluralize(review.endorsements.count) %>
              <%= "Rated:  #{review.rating} out of 5" %> <br>
            <% end %>
          <% end %>

          <div class="review-button">
            <div class="btn-group btn-group-sm" role="group" aria-label="...">
              <% if restaurant.user == current_user %>
                <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant), :class => 'btn btn-default' %>
                <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete, :class => 'btn btn-default' %>
              <% end %>

              <% if current_user %>
                <% if current_user.has_reviewed?(restaurant) %>
                  <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant), :class => 'btn btn-default', :disabled => 'disabled' %>
                <% else %>
                  <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant), :class => 'btn btn-default' %>
                <% end %>
              <% end %>
            </div>
          </div>

        </div>
      </div>
    </div>
  <% end %>

<% else %>
  <h1>No restaurants yet</h1>
<%end%>

<%= link_to "Add a restaurant", new_restaurant_path, :class => 'btn btn-primary' %>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors">
    <h2> <%= pluralize(@restaurant.errors.count, "error") %>
    prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  </section>
<% end %>



<div class="col-md-6 col-md-offset-3">
  <h3 class="text-center">Add Restaurant</h3>
  
  <%= render "form" %>

</div>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit "Leave Review" %>
<% end %>